---
area/github:
  - changed-files: [{any-glob-to-any-file: ".github/**/*"}]

area/kubernetes:
  - changed-files: [{any-glob-to-any-file: "apps/**"}]

area/terragrunt:
  - changed-files: [{any-glob-to-any-file: "infrastructure/**"}]

area/tofu:
  - changed-files: [{any-glob-to-any-file: "**.tofu"}]
area/tofu/proxmox:
  - changed-files: [{any-glob-to-any-file: "infrastructure/proxmox/**"}]
area/tofu/mikrotik:
  - changed-files: [{any-glob-to-any-file: "infrastructure/mikrotik/**"}]

area/talos:
  - changed-files: [{any-glob-to-any-file: "talos/**"}]
