---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-1password
spec:
  path: ./apps/external-secrets/1password
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 1h
  prune: true
  targetNamespace: external-secrets

  dependsOn:
    - name: external-secrets-operator

  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: onepassword
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
