---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
spec:
  path: ./apps/external-secrets/operator
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 10m
  prune: true
  wait: true
  targetNamespace: external-secrets

  dependsOn:
    - name: cert-manager
      namespace: cert-manager
