---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-operator
spec:
  path: ./apps/capi-system/operator
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 1h
  prune: true
  targetNamespace: capi-system
