---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-providers
spec:
  path: ./apps/capi-system/providers
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 1h
  prune: true
  wait: true
  targetNamespace: capi-system

  dependsOn:
    - name: capi-operator
