apiVersion: v1
kind: Secret
metadata:
    name: github-org-token
stringData:
    github_token: ENC[AES256_GCM,data:ySRGfkkQolBo8aV6Cdb5q5UPOC/LnjeD6A2q3z5M4FK6Azu4wupeWw==,iv:kUu9SAge2Vw3e8vD9ptgGAIaU9qp7AoE/vE0+2ZcbP8=,tag:jJa4QFX28YqJ5l3VA4q/Rg==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta05DNTJtU1RXOVZZYVov
            eEhSbVU2U1N1b09jYmlOYTZWR2FFUlplcDBZCjI1Mm10RUNLMEkvQlBEakJLeDcx
            Z3crU1llMEpyV2hpUDFjMExoRUc3cUUKLS0tIE54VU5VYUVLOHlxcUxuYmF5YUFx
            S1R1dEduSjJCV1lTcVY1dklmZWVNdmsKxV/Bc4y+yNHtJIEBOJb04uoQPQd9Ggyu
            YgFOnehB5uIi2aNFLAbhfKdINMvDSklcaHt2yqTSXcyYxUwjcT7oEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T21:56:19Z"
    mac: ENC[AES256_GCM,data:TRhHaltPD/K1/Od6VbeF7EgoEm8wSou4c+lCBqGpdiXu7bbKM2A+UeV8of96eNiZ7G4RFETa5vSKCSp/Va5GbNn3x/9xLQBDVRYumgZFcrxR1iIDwMU7NXbfFVeuqS7Nyz6EZuhJf8ZlAjEneATcuXDqX3RKkoApuMs8S31WJ6s=,iv:l9eLuKPe8lV48LOxw8jjYqGDrLlVLpf5nkHXfJkmwgc=,tag:Na+z4iYnQlukvaHDa9rouw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
