---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-provider-talos
spec:
  path: ./apps/capi-provider-talos/provider
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 1h
  prune: true
  wait: true
  targetNamespace: capi-provider-talos

  dependsOn:
    - name: capi-operator
      namespace: capi-operator

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cabpt-controller-manager
      namespace: capi-provider-talos
    - apiVersion: apps/v1
      kind: Deployment
      name: cacppt-controller-manager
      namespace: capi-provider-talos
