---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-actions-runners
spec:
  path: ./apps/github-actions/runners
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 10m
  prune: true
  wait: false
  targetNamespace: github-actions

  dependsOn:
    - name: github-actions-controller
      namespace: github-actions
    - name: openebs
      namespace: openebs-system
