---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: github-actions-runners
spec:
    path: ./apps/github-actions/runners
    sourceRef:
        kind: GitRepository
        name: home-ops-automaton
        namespace: flux-system

    interval: 1h
    prune: true
    targetNamespace: github-actions

    dependsOn:
        - name: github-actions-controller
          namespace: github-actions
        - name: openebs
          namespace: openebs-system
