---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  # renovate: datasource=github-releases depName=kubernetes-sigs/cluster-api
  version: v1.11.3

  deployment:
    replicas: 1 #! TODO: Set to 2 or more when adding more nodes
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: cluster.x-k8s.io/provider
                  operator: In
                  values: ["cluster-api"]
            topologyKey: kubernetes.io/hostname

    containers:
      - name: manager
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 256Mi
