---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: home-ops
spec:
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: TalosControlPlane
    name: home-ops

  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ProxmoxCluster
    name: home-ops

  controlPlaneEndpoint:
    host: 10.0.0.30
    port: 6443
