---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: home-ops
spec:
  allowedNodes: [pve01, pve02, pve03]
  schedulerHints: {memoryAdjustment: 100}

  controlPlaneEndpoint:
    host: 10.0.0.30 #! must match the Talos VIP IP
    port: 6443

  dnsServers: ["10.0.0.1"]
  ipv4Config:
    gateway: 10.0.0.1
    prefix: 24
    addresses: [10.0.0.31-10.0.0.59]

---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: home-ops
spec:
  paused: false # set to true to pause reconciliation
  controlPlaneEndpoint:
    host: 10.0.0.30 #! must match the Talos VIP IP
    port: 6443

  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: TalosControlPlane
    name: home-ops

  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ProxmoxCluster
    name: home-ops
