---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: home-ops
spec:
  allowedNodes: [pve01, pve02, pve03]

  schedulerHints:
    memoryAdjustment: 0

  controlPlaneEndpoint:
    host: 10.0.0.30
    port: 6443

  dnsServers: ["10.0.0.1"]
  ipv4Config:
    gateway: 10.0.0.1
    prefix: 24
    addresses: [10.0.0.31-10.0.0.59]
