---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: home-ops
spec:
  version: v1.34.1 # TODO: renovate annotation
  replicas: 3

  # TODO: move machine template to capi-system?
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: home-ops
    namespace: capi-cluster-home-ops

  controlPlaneConfig:
    controlplane:
      generateType: controlplane

      strategicPatches:
        - |-
          - op: replace
            path: /machine/install
            value:
              disk: /dev/sda
              extensions:
                - image: registry.home.mirceanton.com/ghcr.io/siderolabs/qemu-guest-agent:10.1.2
          - op: add
            path: /machine/install/extraKernelArgs
            value:
              - net.ifnames=0
          - op: add
            path: /machine/network/interfaces
            value:
              - interface: eth0
                dhcp: false
                vip:
                  ip: 10.0.0.30
