---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: AddonProvider
metadata:
  name: helm
spec:
  # renovate: datasource=github-releases depName=kubernetes-sigs/cluster-api-addon-provider-helm
  version: v0.4.2

  deployment:
    replicas: 1 #! TODO: Set to 2 or more when adding more nodes
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #             - key: cluster.x-k8s.io/provider
    #               operator: In
    #               values: ["helm"]
    #         topologyKey: kubernetes.io/hostname

    containers:
      - name: manager
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 256Mi
