---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cluster-api-operator
      version: 0.24.0
      interval: 5m0s
      sourceRef:
        kind: HelmRepository
        name: cluster-api-operator

  values:
    replicaCount: 1
    leaderElection: {enabled: true}

    logLevel: 2

    resources:
      manager:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
