---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cluster-api-operator
      version: 0.24.0
      interval: 5m0s
      sourceRef:
        kind: HelmRepository
        name: cluster-api-operator

  values:
    # Disable Helm hooks to prevent issues with FluxCD reconciling
    enableHelmHook: true

    # CAPI operator deployment options
    logLevel: 2
    replicaCount: 1
    leaderElection: {enabled: true} #? not needed with single replica?
    resources:
      manager:
        limits:
          cpu: 100m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 100Mi

    # CAPI provider options
    addon:
      helm:
        namespace: capi-system
        #version?

    bootstrap:
      talos:
        # TODO: renovate annotation
        # https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/releases/
        version: v0.6.10
        namespace: capi-system

    controlPlane:
      talos:
        # TODO: renovate annotation
        # https://github.com/siderolabs/cluster-api-control-plane-provider-talos/releases/
        version: v0.5.11
        namespace: capi-system

    core:
      cluster-api:
        namespace: capi-system
        #version?

    infrastructure:
      proxmox:
        # TODO: renovate annotation
        # https://github.com/ionos-cloud/cluster-api-provider-proxmox/releases
        version: v0.7.5
        namespace: capi-system

    ipam:
      in-cluster:
        namespace: capi-system
        #version?
