---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller

  values:
    # ====================================================================
    # =========================== App Settings ===========================
    # ====================================================================
    flags:
      logLevel: info # debug, info, warn, error
      logFormat: text # json, text
      runnerMaxConcurrentReconciles: 5
      updateStrategy: immediate # immediate, eventual

    # ====================================================================
    # ====================== Scaling and Scheduling ======================
    # ====================================================================
    replicaCount: 1 #! TODO: Set to 2 or more when adding more nodes
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        #! FIXME Should be DoNotSchedule but single node clusters can't satisfy that
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: actions-runner-controller
            app.kubernetes.io/instance: actions-runner-controller

    # ====================================================================
    # ======================= Resource Allocations =======================
    # ====================================================================
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # ====================================================================
    # ============================= Security =============================
    # ====================================================================
    podSecurityContext: {fsGroup: 1000}
    securityContext:
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
