---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller

  values: {}
