---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: proxmox-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PROXMOX_URL: "{{ .proxmox_url }}"
        PROXMOX_TOKEN: "{{ .username }}!{{ .token_name }}"
        PROXMOX_SECRET: "{{ .api_token_secret }}"

  data:
    - secretKey: proxmox_url
      remoteRef:
        key: "CapMox Credentials"
        property: "proxmox url"

    - secretKey: username
      remoteRef:
        key: "CapMox Credentials"
        property: "username"

    - secretKey: token_name
      remoteRef:
        key: "CapMox Credentials"
        property: "token name"

    - secretKey: api_token_secret
      remoteRef:
        key: "CapMox Credentials"
        property: "api token secret"
