---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: proxmox
spec:
  # renovate: datasource=github-releases depName=ionos-cloud/cluster-api-provider-proxmox
  version: v0.7.5

  configSecret:
    name: proxmox-credentials

  deployment:
    replicas: 1 #! TODO: Set to 2 or more when adding more nodes
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: cluster.x-k8s.io/provider
                  operator: In
                  values: ["infrastructure-proxmox"]
            topologyKey: kubernetes.io/hostname

    containers:
      - name: manager
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
