---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  # renovate: datasource=github-releases depName=kubernetes-sigs/cluster-api
  version: v1.11.3
