---

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword.external-secrets.svc.cluster.local
      vaults:
        Automation: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-token
            namespace: external-secrets
            key: token
