---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openebs
spec:
    interval: 10m
    chartRef:
        kind: OCIRepository
        name: openebs

    values:
        localpv-provisioner:
            analytics: {enabled: false}
            localpv:
                image:
                    registry: quay.io/
                basePath: &hostPath /var/mnt/data
            hostpathClass:
                enabled: true
                name: openebs-hostpath
                isDefaultClass: false
                basePath: *hostPath
            helperPod:
                image:
                    registry: quay.io/

        openebs-crds:
            csi:
                volumeSnapshots:
                    enabled: false
                    keep: false

        preUpgradeHook: {enabled: false}

        zfs-localpv: {enabled: false}
        lvm-localpv: {enabled: false}
        mayastor: {enabled: false}
        loki: {enabled: false}
        alloy: {enabled: false}
        minio: {enabled: false}
        engines:
            local:
                lvm: {enabled: false}
                zfs: {enabled: false}
            replicated:
                mayastor: {enabled: false}
