---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: openebs

  values:
    localpv-provisioner:
      analytics: {enabled: false}

      localpv:
        basePath: &hostPath /var/mnt/data
        requests:
          cpu: 50m
          memory: 75Mi
        limits:
          cpu: 100m
          memory: 150Mi

      hostpathClass:
        enabled: true
        name: openebs-hostpath
        reclaimPolicy: Delete
        isDefaultClass: false
        basePath: *hostPath

    alloy: {enabled: false}
    loki: {enabled: false}
    engines:
      local:
        lvm: {enabled: false}
        zfs: {enabled: false}
      replicated:
        mayastor: {enabled: false}
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
