---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-helm-proxies
spec:
  path: ./apps/capi-clusters/helm
  sourceRef:
    kind: GitRepository
    name: home-ops-automaton
    namespace: flux-system

  interval: 1h
  prune: true
  wait: false
  targetNamespace: capi-clusters

  dependsOn:
    - name: capi-provider-proxmox
      namespace: capi-provider-proxmox
    - name: capi-provider-talos
      namespace: capi-provider-talos
    - name: capi-provider-helm
      namespace: capi-provider-helm
