---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: IPAMProvider
metadata:
  name: in-cluster
spec:
  # renovate: datasource=github-releases depName=kubernetes-sigs/cluster-api-ipam-provider-in-cluster
  version: v1.0.3

  spec:
    deployment:
      replicas: 1 #! TODO: Set to 2 or more when adding more nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: cluster.x-k8s.io/provider
                    operator: In
                    values: ["ipam-in-cluster"]
              topologyKey: kubernetes.io/hostname

      containers:
        - name: manager
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
